apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: angular-15-client-tutorialsonline
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: angular-15-client-tutorialsonline
    app.kubernetes.io/part-of: tutorialsonline
  name: angular-15-client-tutorialsonline
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: angular-15-client-tutorialsonline
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: angular-15-client-tutorialsonline
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/atul-fulambarkar-tenant/tutorialsonline/angular-15-client-tutorialsonline@sha256:1ab762498775321548b1d6f37a00a483771557f2de7479730d8f285302dcbc1a
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
