apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: spring-boot-server-tutorialsonline
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: spring-boot-server-tutorialsonline
    app.kubernetes.io/part-of: tutorialsonline
  name: spring-boot-server-tutorialsonline
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: spring-boot-server-tutorialsonline
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: spring-boot-server-tutorialsonline
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/atul-fulambarkar-tenant/tutorialsonline/spring-boot-server-tutorialsonline@sha256:f858154db0abe7766b37099eeb31205b89e7c69b3f21a0bd89b4bce08cdbaac8
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
